### ISSUE TITLE
MaterialBasedCupertinoThemeData isn't defined for the class PlatformApp

### ISSUE THREAD

**Issue by samanzamani** [fuzz-productions/platty#2]
Hi
I try use `PlatformApp` but i got this error message.

> Error: The method 'MaterialBasedCupertinoThemeData' isn't defined for the class '#lib1::PlatformApp'.
> Try correcting the name to the name of an existing method, or defining a method named 'MaterialBasedCupertinoThemeData'.
>             MaterialBasedCupertinoThemeData(materialTheme: unifiedTheme),
>

**Comment by ghost** [comment]
Same error for me, even when building the example:

flutter: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
flutter: The following _CompileTimeError was thrown building MyApp(dirty):
flutter: 'package:platty/src/platform_app.dart': error: line 65 pos 13:
flutter: file:///Users/tom/Code/platty/lib/src/platform_app.dart:65:13: Error: The method
flutter: 'MaterialBasedCupertinoThemeData' isn't defined for the class '#lib1::PlatformApp'.
flutter: Try correcting the name to the name of an existing method, or defining a method named
flutter: 'MaterialBasedCupertinoThemeData'.
flutter:             MaterialBasedCupertinoThemeData(materialTheme: unifiedTheme),
flutter:             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
flutter:             MaterialBasedCupertinoThemeData(materialTheme: unifiedTheme),
flutter:             ^
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      MyApp.build 
package:example/main.dart:12
flutter: #1      StatelessElement.build 
package:flutter/…/widgets/framework.dart:3774
flutter: #2      ComponentElement.performRebuild 
package:flutter/…/widgets/framework.dart:3721
flutter: #3      Element.rebuild 
package:flutter/…/widgets/framework.dart:3547
flutter: #4      ComponentElement._firstBuild 
package:flutter/…/widgets/framework.dart:3701
flutter: #5      ComponentElement.mount 
package:flutter/…/widgets/framework.dart:3696
flutter: #6      Element.inflateWidget 
package:flutter/…/widgets/framework.dart:2950
flutter: #7      Element.updateChild 
package:flutter/…/widgets/framework.dart:2753
flutter: #8      RenderObjectToWidgetElement._rebuild 
package:flutter/…/widgets/binding.dart:909
flutter: #9      RenderObjectToWidgetElement.mount 
package:flutter/…/widgets/binding.dart:880
flutter: #10     RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> 
package:flutter/…/widgets/binding.dart:826
flutter: #11     BuildOwner.buildScope 
package:flutter/…/widgets/framework.dart:2266
flutter: #12     RenderObjectToWidgetAdapter.attachToRenderTree 
package:flutter/…/widgets/binding.dart:825
flutter: #13     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.attachRootWidget 
package:flutter/…/widgets/binding.dart:712
flutter: #14     runApp 
package:flutter/…/widgets/binding.dart:756
flutter: #15     main 
package:example/main.dart:6
flutter: #16     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:289:19)
flutter: #17     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
